//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Детали_заказа> Детали_заказа { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Категории> Категории { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Производители> Производители { get; set; }
        public virtual DbSet<Пункты_выдачи> Пункты_выдачи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Статусы> Статусы { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
    }
}
