//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Детали_заказа
    {
        public int ID { get; set; }
        public int Номер_заказа { get; set; }
        public int ID_товара { get; set; }
        public int Количество_товара { get; set; }
        public decimal Цена_на_момент_заказа { get; set; }
    
        public virtual Товары Товары { get; set; }
        public virtual Заказы Заказы { get; set; }
    }
}
