//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Детали_заказа = new HashSet<Детали_заказа>();
        }
    
        public int ID { get; set; }
        public string Артикул { get; set; }
        public string Наименование_товара { get; set; }
        public string Единица_измерения { get; set; }
        public decimal Цена { get; set; }
        public int Поставщик { get; set; }
        public int Производитель { get; set; }
        public int Категория_товара { get; set; }
        public decimal Действующая_скидка { get; set; }
        public int Колво_на_складе { get; set; }
        public string Описание_товара { get; set; }
        public string Фото { get; set; }
        public Nullable<int> Скидка { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Детали_заказа> Детали_заказа { get; set; }
        public virtual Категории Категории { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Производители Производители { get; set; }
    }
}
